spring:
  datasource:
    username: ${JDBC_DATABASE_USER}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
    hikari:
      maximum-pool-size: 30
logging:
  level:
    root: debug
jwt:
  issuer: ${JWT_ISSUER}
  expireMinutes: ${JWT_EXPIRE_MINUTES}
  secretKey: ${JWT_SECRET_KEY}
