spring:
  datasource:
    username: ${JDBC_DATABASE_USER}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
    hikari:
      maximum-pool-size: 30
logging:
  level:
    root: info
jwt:
  issuer: "hexlet-blog"
  expireMinutes: 30
  secretKey: "test-key"
