spring:
  profiles:
    active: ${PROFILE:prod}
  application:
    name: "hexletBlog"
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
base-api-url: /api
springdoc:
  swagger-ui:
    path: /swagger.html