spring:
  datasource:
    url: jdbc:h2:./blog
    username: user
    password: password
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    root: debug
jwt:
  issuer: hexlet-blog
  expireMinutes: 30
  secretKey: "test-secret"